# Generated by Django 3.1 on 2020-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('planks', 'Planks'), ('burpees', 'Burpees'), ('crunches', 'Crunches'), ('steps', 'Steps'), ('miles', 'Miles'), ('pullups', 'Pullups'), ('squats', 'Squats'), ('pushups', 'Pushups'), ('sunsalutes', 'Sun Salutes')], default='planks', max_length=200)),
                ('sms_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('exercises', models.ManyToManyField(related_name='challenger', to='core.Exercise')),
            ],
        ),
    ]
