# Generated by Django 3.1 on 2020-08-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200820_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('challenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.challenger')),
            ],
            options={
                'verbose_name_plural': 'columns',
                'db_table': 'column',
            },
        ),
    ]
