# Generated by Django 3.1 on 2020-08-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercise'),
        ),
    ]
