# Generated by Django 3.1 on 2020-08-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_column_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='timezone',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='challenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column', to='core.challenger'),
        ),
    ]
