# Generated by Django 3.1 on 2020-08-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200821_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
